### ISSUE TITLE
Skypeweb login with Live account - "Failed getting Skype Token"

### ISSUE THREAD

**Issue by phpony** [EionRobb/skype4pidgin#281]
I have 2 skype accounts. One is regular old one, created more than 5 years ago, and it works well with latest build. The second one is a live account with login like ********@outlook.com. And it doesn't work - fails with message "Failed getting Skype Token".

I think it's because this type of accounts are being redirected to different auth form. Is it possible to make Live accounts work?

Can provide debug log on request.

**Comment by phpony** [comment]
Oh. I should read more carefully:

> Until I get MSN/Live logins going there won't be any releases on GitHub.

So, looks like Live logins support is probably just a question of time. Sorry for disturbing.

**Comment by EionRobb** [comment]
Would be good to keep track of somewhere so that people can +1 it and all that :)

**Comment by oldmud0** [comment]
Great that this was reported 2 days ago and not 4 months ago :smile:

**Comment by drzraf** [comment]
Trying to move this forward.
AFAICT it's plain oauth2 that is used by skype while requesting microsoft as an oauth2 provider.
- is there a GPL-compatible C liboauth2 available (seems like no)
- if not : create it or call a python/perl/php/whatever script... to do this ? or do the transaction manually ?
It should follow the oauth flow and **that means user intervention** (probable UI/usability issue), and a few gain in storing user credentials.

I don't know about oauth2. But all implementation start with a user ID and a token.
Should this token be given to the plugin by the user initially or can it be grab using username/password? (there are temporary token, needed to refresh/keep-alive authentication, and a more permanent token which, once received by the plugin, should be stored)

**Comment by EionRobb** [comment]
The problem with oauth is that it generally needs a web browser, which can't always be assumed (eg, try using Finch, or a command-line bot or something)

On the plus side, the miranda guys have been working on a protocol plugin of their own and have Live logins working http://trac.miranda-ng.org/browser/trunk/protocols/SkypeWeb/src/skype_mslogin.cpp

Patches always welcome! :)

**Comment by drzraf** [comment]
On Wed, Jun 17, 2015 at 12:41:48AM -0700, Eion Robb wrote:
> On the plus side, the miranda guys have been working on a protocol plugin of their own and have Live logins working http://trac.miranda-ng.org/browser/trunk/protocols/SkypeWeb/src/skype_mslogin.cpp

that's great. It seems they are parsing HTML, storing/sending cookies,
... as would do the web browser during an oauth transaction.
Hopefully m$ won't break the markup anytime soon...
For @-logins they have a new LoginMSRequest handled with
OnMSLoginFirst() and for the other a LoginOAuthRequest() handled by
OnLoginOAuth.

But I thought @-less logins where "regular" skype account
while @-live.com login where using m$ oauth2. Isn't that true?


One issues I hit when working on a patch was that I needed to intercept
a Set-Cookie value issued by HTTP 301 response (redirect) of
live.com. [I'm 70% confident it's needed]
At the time of testing (2 months ago) libpurple 2.10 didn't
handle that (would follow the redirect without giving a chance to grab
the cookies). I hoped that a switch to libcurl would solve it but it
seems it didn't got in (but actually I don't know anything about libpurple3
changes).

**Comment by EionRobb** [comment]
@drzraf I'm working on splitting out the "plain" http requests as part of the purple3 migration, but for now you can hack it to not automatically redirect in a similar way to https://github.com/EionRobb/skype4pidgin/blob/8dd7167b84addb1afa6f1e8d93021b7d7fd63d05/skypeweb/skypeweb_messages.c#L867 by tricking libpurple into thinking it's already followed it's maximum number of redirects.   Appreciate you looking into a patch :)

**Comment by EionRobb** [comment]
So, as of a few commits ago, there's support for Live logins, if you want to give it a try

**Comment by oldmud0** [comment]
Actually I thought live login used Passport1.4?

**Comment by phpony** [comment]
My  ********@outlook.com account finally works! Oh, I'm wiping the Skype out of my laptop with such a happy face now... Take my appreciation and $25 donation, thanks! :)

**Comment by oldmud0** [comment]
Can't do that until I get video and voice with Pidgin... (Windows)

**Comment by szr8** [comment]
When I try logging in with my MSN/Live account, the connect fails with "Failed getting Magic T value" shown at the bottom of the contact list.

**Comment by bvarent** [comment]
Although this issue is about support for live logins. I've had the same symptoms even after that support was added. In my case updating pidgin windows from 2.10.9 to 2.10.11 fixed it. (No surprise, since pidgin.im states: "Pidgin 2.10.11 contains login fixes for MSN and some XMPP servers, and Pidgin 2.10.10 contains important security updates. Please upgrade!") Thought I'd add that here for people googling "Failed getting Skype Token".

**Comment by LennyLip** [comment]
same message with password, more then 8 characters (libpurbple bug). 
chage pass to 8 and all ok now.

**Comment by smokeyser** [comment]
I'm getting the same message with an 8 character password using the latest pidgin and skypeweb downloaded today.  Thankfully the old plugin still works.  :)

**Comment by drzraf** [comment]
beaten today, (using a 8 characters password, in case it's really related)

**Comment by MintPaw** [comment]
It fails for me with or without an 8 character password, this is a pretty big deal.

**Comment by thelostt** [comment]
"Failed getting Registration Token"

Got it out of nowhere. I can't login anymore.

**Comment by bvarent** [comment]
make sure you have the latest version ([1.1](https://github.com/EionRobb/skype4pidgin/releases/tag/1.1) now) in which the logon URL was changed to address these symptoms.

**Comment by tssk** [comment]
Hello, I also started getting "Failed getting Registration Token" with my classic skype login (not live account). I am using 1.1 version.

**Comment by MintPaw** [comment]
Building and updating to version 1.1 [using these instruction](https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#building-aur-package-for-arch-linux) and the issue was solved, it hasn't been updated on the Arch Aur it seems, so a lot of people will randomly have this issue.

**Comment by thelostt** [comment]
> Building and updating to version 1.1 using these instruction and the issue was solved, it hasn't been updated on the Arch Aur it seems, so a lot of people will randomly have this issue.

Worked for me as well.

**Comment by opensamba** [comment]
confirm.
> aur/purple-skypeweb 1.1-2 [installed] (13)

still having problem randomly with the skypeweb account:
"""
ERROR: Failed getting Registration Token
"""

**Comment by drzraf** [comment]
beaten randomly too.
restarting pidgin usually solved it.

**Comment by xvitaly** [comment]
@opensamba SkypeWeb API is down.

**Comment by oldmud0** [comment]
That's nice, let's just hope it doesn't stay down forever.

**Comment by rudeblunt** [comment]
Any news?

**Comment by opensamba** [comment]
2 days which is working for me, let's hope this is stable

**Comment by MintPaw** [comment]
This is still happening, specifically, when I sign into the Android client and sign out again, I get the registration token error when trying to connect with Pidgin for at least 30min after. Turning off my phone and uninstalling the app doesn't fix this.
Changing my password using the Skype web interface allows me to sign in, I can change it back to the original password after and it continues to work.

**Comment by zevelorgani** [comment]
Since upgrading to pidgin 2.11 I'm getting the dreaded Failed getting Registration Token
Please advise

**Comment by jeffhuang** [comment]
Getting the same thing as @zevelorgani

**Comment by zevelorgani** [comment]
Forgot to say that I got a debug version of the DLL from Eion and it solved the problem.
He said he'll publish the final soon

**Comment by ptkovsky** [comment]
Yea same stuff here guys. New pidgin version probably broke something here. Just updated and getting registration/skype token errors all over the place.

**Comment by xvitaly** [comment]
@ptkovsky Install updated version: http://eion.robbmob.com/libskypeweb-debug.dll

**Comment by ptkovsky** [comment]
@xvitaly Done. Logged in without errors, at least for now. Thank you very much.

**Comment by WuTianming** [comment]
Arch Linux x86,
Pidgin 2.11.0 (libpurple 2.11.0), f02ebb71b5e32cc4af521e7f89c34dedff8d09ae,
community/purple-skypeweb 1.1-1 installed.
All the packages are at the newest version in the official repository.
How to login with a live account?
I tried "live:xxxxx@xxx.com", but got a error "Failed getting Magic T value".
Anyone can help? Thanks!

**Comment by M5rl** [comment]
Yea im getting the "Failed getting Registration Token" error now.

**Comment by Zaros104** [comment]
Getting this issue as well... Running Pidgin 2.11.0-1 with purple-skypeweb 1.1-2 compiled from the GIT earlier today. Debug shows that it resolved DNS, connects through 'proxy' (there is none), verifies cert, and sends the request. The return response has a 'Connection: close'.

**Comment by xvitaly** [comment]
> purple-skypeweb 1.1-2 compiled from the GIT earlier today

Revision 72f0b003252d0c827e9fa5dcb31005ef4a51b036? Version 1.1-2 means that your are using old and outdated SPEC. Use a new one from [Fedora's upstream](http://pkgs.fedoraproject.org/cgit/rpms/purple-skypeweb.git/tree/purple-skypeweb.spec).

**Comment by Zaros104** [comment]
> Revision 72f0b00? Version 1.1-2 means that your are using old and outdated SPEC which uses releases tarballs, not Git snapshots. Use a new one from Fedora's upstream.

Perfect! Compiled with the new SPEC and it worked perfectly. Any plans to update the AUR/GIT in the near future?

**Comment by dequis** [comment]
The original issue is fixed, the rest of the comments mention unrelated issues that are either server issues or stuff that is fixed in the current version. Closing this.
