### ISSUE TITLE
Constant Request: SSL Certificate Verification using bitlbee (Skypeweb)

### ISSUE THREAD

**Issue by dmarkey** [EionRobb/skype4pidgin#290]
22:52 <@root> Accepted: Request: SSL Certificate Verification
22:52 <@root>
22:52 <@root> Accept certificate for api.skype.com?
22:52 <@root>
22:52 <@root> The certificate for api.skype.com could not be validated.
22:52 <@root>
22:52 <@root> The certificate is not trusted because no certificate that can verify it is currently trusted.

This happens once every few minutes, and messages are stalled until its accepted.

**Comment by EionRobb** [comment]
I wonder if it's related to #289 ?

**Comment by EionRobb** [comment]
Any luck getting things working?  If not, feel free to reopen :)

**Comment by dar72** [comment]
For me this was a bitlbee issue rather than an issue with this plugin

Run bitlbee like this:
BITLBEE_DEBUG=1 /usr/sbin/bitlbee -nD

In my case I was getting:
DEBUG util: Error opening file /var/lib/bitlbee//purple/d72/certificates/x509/tls_peers/api.skype.com.save for writing: No such file or directory

Which seemed to keep causing this:
DEBUG certificate/x509/tls_cached: Starting verify for api.skype.com
DEBUG certificate/x509/tls_cached: Checking for cached cert...
DEBUG certificate/x509/tls_cached: ...Not in cache

Create the directory:
sudo mkdir -p /var/lib/bitlbee/purple/<BITLBEE_USERNAME>/certificates/x509/tls_peers/


That fixed it for me on Arch

**Comment by rodneyrod** [comment]
I'm going to leave this here if anyone else might need to see it.

The version of Bitlbee that ships with stable distros like Debian or Ubuntu LTS doesn't work with the latest SkypeWeb plugin, it fails to fetch the login token.
Manually adding bitlbee's latest repos rectifies this issue.

**Comment by arnottcr** [comment]
I am running bitblee-libpurple 3.4.1, skypeweb 1.0 and libpurple 2.10.11 on an archlinux host. I can confirm the same issue and have found a related bug in the bitlbee bug tracker: https://bugs.bitlbee.org/bitlbee/ticket/910

Not sure if it is related, because the fix should have been merged into 3.0.4 and I am on 3.4.1, but the resolution is eerily similar.

**Comment by EionRobb** [comment]
@arnottcr 3.0.4 is the version of bitlbee it was reported with, I don't think there's been a new release of bitlbee since the fix

**Comment by arnottcr** [comment]
you are completely correct [this](https://github.com/bitlbee/bitlbee/commit/e4c3041a398adb7ac938e0e3cd62ef52247658ad) is the commit that fixed the issue (october 25), and it looks like the most recent version is 3.4.1 (june 16). So, the next release should fix this issue. Till then I may try to get a git version of the aur package working.

Either way, this does not look like an issue with your code and I feel comfortable saying that you can close the issue for good.

**Comment by ldanet** [comment]
I know it is not related with this plugin's code, but for anyone stumbling here looking for a fix, creating a generic directory did not work for me. What worked was 
`sudo mkdir -p /var/lib/bitlbee//purple/user/certificates/x509/tls_peers/`
replacing `user` with my user name.

I'm running bitlbee on Arch too.

**Comment by xvitaly** [comment]
> I know it is not related with this plugin's code, but for anyone stumbling here looking for a fix, creating a generic directory did not work for me.

I think you should open ticket in Bitlbee's bug tracker because it is not even purple issue. Libpurple-based clients stores certificates in ~/.purple/certificates/x509/tls_peers/ directory.

**Comment by dequis** [comment]
What @ldanet described is exactly what was fixed by [that commit](https://github.com/bitlbee/bitlbee/commit/e4c3041a398adb7ac938e0e3cd62ef52247658ad)

The bug was that the directory did not exist, that commit creates it automatically, or you can just create the directory yourself with that command. Ensure that it's writable by the user bitlbee is running as.

Also yes please close this.

**Comment by EionRobb** [comment]
Thanks @dequis

**Comment by Zauberfisch** [comment]
For me this issue still persist on arch linux (community/purple-skypeweb 1.2.1-1).

The problem seems to be both folder and permissions. I am running bitlbee as user bitlbee.

    [root@hostname /]# cd /var/lib/bitlbee/
    [root@hostname bitlbee]# ls -al
    total 20
    drwxrwx---  3 bitlbee bitlbee 4096 Oct 10 12:47 .
    drwxr-xr-x 15 root    root    4096 Oct 11 03:00 ..
    drwx------  3 root    root    4096 Oct 10 11:32 purple
    -rw-------  1 bitlbee bitlbee    0 Oct 10 12:47 MyBitlbeeIRCNick.otr_fprints
    -rw-r--r--  1 bitlbee bitlbee  134 Oct 10 12:30 MyBitlbeeIRCNick.otr_instags
    -rw-------  1 bitlbee bitlbee  328 Oct 10 12:47 MyBitlbeeIRCNick.xml

see how the folder purple is owned by root instead of bitlbee. Could be that I have configured bitlbee to use the user bitlbee after installing purple though.
Additionally I had to create a folder (like others have suggested before me).

So I fixed it with:

    [root@hostname /]# mkdir -p /var/lib/bitlbee/purple/{MyBitlbeeIRCNick}/certificates/x509/tls_peers/
    [root@hostname /]# chown -R bitlbee:bitlbee /var/lib/bitlbee/purple/

make sure you replace `{MyBitlbeeIRCNick}` with the irc nick you use in bitlbee, not a linux username.
