### ISSUE TITLE
Cannot login via skypeweb with MSN/Live email address; "Failed getting Magic T value"

### ISSUE THREAD

**Issue by szr8** [EionRobb/skype4pidgin#297]
I can login with Skypeweb in Pidgin 2.10.11 using a skypename just fine but not with an MSN/Live account (that is associated with the skypename that worked.) The connection attempt fails with "Failed getting Magic T value." I've seen some posts lately stating that Live/MSN logins were working with the recent builds so I'm not sure what I might be doing wrong (or if something is going on on the server end perhaps.)

I am using 99383c451ca9322400d78db9dd5cabf47f910381 but I had gotten the same error with 882616db8cef34bb3f5c8647a7849eb7ba09f443.

Debug log: https://gist.github.com/szr8/0a00699bc685dfd4d8e9

Thanks.

**Comment by EionRobb** [comment]
If you login to web.skype.com with that Live account, does it work, or does it ask you to accept an agreement or push a button etc?

**Comment by szr8** [comment]
I went to web.skype.com and entered my Live/MSN account and before I could enter the password (when I hit tab) it took me to <a href="https://login.live.com/login.srf?wa=wsignin1.0&rpsnv=12&ct=1436915028&rver=6.6.6577.0&wp=MBI_SSL&wreply=https:%2F%2Fsecure.skype.com%2Flogin%2Foauth%2Fproxy%3Fclient_id%3D578134%26redirect_uri%3Dhttps%253A%252F%252Fweb.skype.com&lc=1033&id=287688&mkt=en-US&username=xxxx%40yyyyyyy.com">here</a>.

Once there it showed me a prompt with my Live account (email) filled in. I then realized that I had been trying the wrong password. I had been trying the skype password that that account had had been merged with.

So the mistake was my own (I should have checked using web.skype.com or so in the first place) and I apologize for that. I guess that's something that can arise from having such a two-sided account and not realizing the password for the legacy side has remained intact.

I would suggest issuing an error to that effect instead of the rather cryptic "Failed getting Magic T value" which makes it looks like something else was afoot.

Thanks.

**Comment by EionRobb** [comment]
I might have to do some captures to see what errors come back with a bad password, so we can pick up on them

**Comment by szr8** [comment]
Sounds good. I know it's very much still in development, so this sort of thing is expected. This is really is a great plugin so far. :)

**Comment by drzraf** [comment]
Got the bad Magic T value, then web-logged-in and accepted the new agreement.
Now the failure is different:
- I'm logged (checkbox ticked)
- In the log I saw XML with nicknames of buddies from MSN
- but they do not show up in the pidgin buddy list:

> (16:29:04) skypeweb: executing callback for /v1/users/ME/endpoints/SELF/subscriptions/0/poll
(12 times)

**Comment by EionRobb** [comment]
@drzraf You're probably referring to #299

**Comment by drzraf** [comment]
indeed; subscribed, let me know how we can help on this one

**Comment by drzraf** [comment]
Got the connection to work after a web connection first. In this case I had a "confirm fallback emails" popup which was keeping skypeweb plugin to succeed.

**Comment by drzraf** [comment]
Tried again today but got the "Failed getting Magic T value", but in this case I had no specific popup when going on web.skype.com and connecting using x@hotmail.com. I'm left without explanation.

**Comment by intrepidIbex** [comment]
Get the error-message by logging in with Live-credentials.
Login over web.skype.com works.
I've attached my log.
[purple-debug.txt](https://github.com/EionRobb/skype4pidgin/files/80323/purple-debug.txt)

**Comment by EionRobb** [comment]
@intrepidIbex Fixed in 1.1 :)

**Comment by intrepidIbex** [comment]
Works for me. Thank you.

**Comment by atmarsden95** [comment]
I'm having this problem:

On an x@outlook.com account, tried logging in with two-factor turned on, using an app password, that didn't work. Disabled 2FA, and tried my normal password, still not working: Consistently getting a "Failed getting Magic T value" error which disables the account.

**Comment by nahuelange** [comment]
Hi, I'm having the same issue, but I can log-in on web.skype.com with no agreement to validate.
There is the error log:
```
15586: 2016-03-03 12:12:48,504 INFO  libpurple: util:parsed 1366
15586: 2016-03-03 12:12:48,505 ERROR backend: g_log skypeweb_string_get_chunk: assertion 'chunk_start' failed
15586: 2016-03-03 12:12:48,505 INFO  libpurple: connection:Connection error on 0x1841660 (reason: 2 description: Failed getting Magic T value)
15586: 2016-03-03 12:12:48,510 INFO  libpurple: account:Disconnecting account myemail@hotmail.com (0x183e700)
15586: 2016-03-03 12:12:48,512 INFO  libpurple: connection:Disconnecting connection 0x1841660
15586: 2016-03-03 12:12:48,512 ERROR backend: GLib g_source_remove: assertion 'tag > 0' failed
15586: 2016-03-03 12:12:48,512 ERROR backend: GLib g_source_remove: assertion 'tag > 0' failed
15586: 2016-03-03 12:12:48,512 ERROR backend: GLib g_source_remove: assertion 'tag > 0' failed
15586: 2016-03-03 12:12:48,513 INFO  libpurple: skypeweb:getting url /logout
15586: 2016-03-03 12:12:48,513 INFO  libpurple: skypeweb:sending headers:
GET /logout HTTP/1.0
Host: login.skype.com
Connection: close
Accept: */*
Cookie: 
Accept-Encoding: gzip
Accept-Language: fr-FR.UTF-8, fr-FR, fr.UTF-8, fr, C
```

I use an …@hotmail.com username and not using the wrong password.
Any idea what's wrong?

**Comment by nahuelange** [comment]
Ok, it was "security" problem with my account, Live.com though it was "suspicious" connection.

**Comment by nitrocode** [comment]
I'm still getting the *Failed getting Magic T value* when I use my full work email as my username.

If I use myname.companyextention (like I use with Skype for Business) then pidgin freezes up. Is anyone seeing a similar issue?

@szr8 are you seeing this still?

**Comment by capitaladot** [comment]
Same issue, here.

**Comment by dequis** [comment]
The original issue in this ticket is fixed, others turned out to be stuff that we cover with the fancy flowchart in https://github.com/EionRobb/skype4pidgin/tree/master/skypeweb#issues

@nitrocode @capitaladot if you're still having issues please check that flowchart, and if it's not covered there, please open a new ticket (hard to track different issues like this). Thanks.

**Comment by MartinX3** [comment]
#385
