### ISSUE TITLE
"Failed getting PPFT value, please try logging in via browser first" but the latter doesn't work

### ISSUE THREAD

**Issue by rvdborgt** [EionRobb/skype4pidgin#663]
I've been seeing this error message quite a lot lately (Pidgin 2.14.1, Windows 10, both on my private and work laptop). It disappeared for a week or so after upgrading to 1.7 but now it's back.
I logged in via the browser but after that the error kept appearing. I also tried the "alternative login method" but that consistently results in "Login error: Bad username or password (Profile accrual is required)". My password _is_ correct though.

Any ideas?

**Comment by bmomjian** [comment]
I got the same error, but using "Alternate Login Method" worked for me.  I did log out and back into the Skype website, in case that helps.

**Comment by bodqhrohro** [comment]
See #660.

The author of that issue actually has a pretty ancient version which obviously has no chances to work, but it already attracted some people affected by the change on M$ side that happened only a day or two ago, as the error message is the same.

**Comment by rvdborgt** [comment]
> See #660.
> 
> The author of that issue actually has a pretty ancient version which obviously has no chances to work, but it already attracted some people affected by the change on M$ side that happened only a day or two ago, as the error message is the same.

Thatnks. Just need to wait for the next Windows build then.

**Comment by bodqhrohro** [comment]
@rvdborgt [1.6](https://github.com/EionRobb/skype4pidgin/releases/download/1.6/libskypeweb.dll) should work too.

**Comment by dazzzl** [comment]
I have the same issue with version 1.7. I haven't tried the alternative login. Maybe Microsoft changed something....

**Comment by dazzzl** [comment]
Fixed by going back to 1.6... :-)

**Comment by alexolog** [comment]
1.7 fixed some other issues, so it would be better (IMHO) to release 1.8 :)

Is the reversal universal or does Skype still present the extra step in some cases?

**Comment by dlmarquis** [comment]
The fix is easy, just revert the change made [here](https://github.com/EionRobb/skype4pidgin/commit/6d6abba7446d6b7b0694af54ec5273463b77a468#diff-de842abc0b0c30b41e733b21e7d2dd91R342) by replacing `skype_login_got_opid` with `skype_login_got_t`. It was line 289 for me.

**Comment by rvdborgt** [comment]
Update: today I enabled the Skype plugin (1.7) again and it worked. So I guess we can close this issue.

**Comment by bmomjian** [comment]
I can confirm I no longer need to use the alternate login for it to work.  Seems this was a bug on the Skype end that has been fixed.
